feat: using render postgresql

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -50,18 +50,18 @@ jobs:
       - name: 🐳 Set up Docker
         uses: docker/setup-buildx-action@v3
 
-      - name: ⬆️ Compose Up
-        run: docker-compose up --build -d
+      # - name: ⬆️ Compose Up
+      #   run: docker-compose up --build -d
 
-      - name: Wait for backend to start
-        run: sleep 5
+      # - name: Wait for backend to start
+      #   run: sleep 5
 
-      - name: 🧪 Run health test
-        run: curl -f http://localhost:3000/ping || exit 1
+      # - name: 🧪 Run health test
+      #   run: curl -f http://localhost:3000/ping || exit 1
 
-      - name: 🧹 Clean up containers
-        if: always()
-        run: docker-compose down
+      # - name: 🧹 Clean up containers
+      #   if: always()
+      #   run: docker-compose down
 
       - name: 🔐 Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v3
